import 'dart:math';

import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'dart:io';
import 'dart:convert';
import 'car_model.dart';
import 'network_call.dart';

class CarView extends StatefulWidget {
  @override
  _CarViewState createState() => _CarViewState();
}

class _CarViewState extends State<CarView> {
  final String url = "https://ven10.co/assessment/filter.json";
  List<Autogenerated> myAllData = [];
  List cars = [
    'assets/car1.jpg',
    'assets/car2.jpg',
    'assets/car3.jpg',
    'assets/car5.jpg',
    'assets/car6.jpg',
    'assets/car.jpg'
  ];

  @override
  void initState() {
    loadData();
  }

  loadData() async {
    var response = await http.get(url, headers: {"Aceept": "application/json"});
    if (response.statusCode == 200) {
      String responseBody = response.body;
      var jsonBody = json.decode(responseBody);
      print(response.body);
      for (var data in jsonBody) {
        myAllData.add(Autogenerated(
            data['id'],
            data['start_year'],
            data['end_year'],
            data['gender'],
            data['countries'],
            data['colors']));
      }
      setState(() {});
      myAllData.forEach((someData) => print("id:${someData.id}"));
    } else {
      print("somthing went wrong");
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: myAllData.length == 0
          ? new Center(
              child: CircularProgressIndicator(),
            )
          : showMyUI(),
    );
  }

  Widget showMyUI() {
    return new ListView.builder(
        itemCount: myAllData.length,
        itemBuilder: (_, index) {
          return new Container(
            margin: new EdgeInsets.symmetric(vertical: 2.0, horizontal: 8.0),
            child: new Card(
              elevation: 10.0,
              child: Row(
                children: <Widget>[
                  Expanded(
                    child: Padding(
                      padding: const EdgeInsets.all(8.0),
                      child: Image(
                        image:
                            AssetImage(cars[index]),//new Random().nextInt(cars.length)
                        fit: BoxFit.contain,
                      ),
                    ),
                  ),
                  SizedBox(width: 10),
                  Expanded(
                    child: new Container(
                      padding: new EdgeInsets.all(12.0),
                      child: new Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: <Widget>[
                          new Padding(
                              padding: new EdgeInsets.symmetric(vertical: 3.0)),
                          new Text('ID : ${myAllData[index].id}'),
                          new Padding(
                              padding: new EdgeInsets.symmetric(vertical: 3.0)),
                          new Text('colors : ${myAllData[index].colors}'),
                          new Padding(
                              padding: new EdgeInsets.symmetric(vertical: 3.0)),
                          new Text('countries: ${myAllData[index].countries}'),
                          new Padding(
                              padding: new EdgeInsets.symmetric(vertical: 3.0)),
                          new Text('endyear : ${myAllData[index].endYear}'),
                          new Padding(
                              padding: new EdgeInsets.symmetric(vertical: 3.0)),
                          new Text('gender: ${myAllData[index].gender}'),
                          new Padding(
                              padding: new EdgeInsets.symmetric(vertical: 3.0)),
                          new Text('startyear : ${myAllData[index].startYear}'),
                          new Padding(
                              padding: new EdgeInsets.symmetric(vertical: 3.0)),
                        ],
                      ),
                    ),
                  ),
                ],
              ),
            ),
          );
        });
  }
}
