import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'dart:io';
import 'dart:convert';
import 'car_model.dart';
import 'network_call.dart';

class FirstView extends StatefulWidget {
  @override
  _FirstViewState createState() => _FirstViewState();
}

class _FirstViewState extends State<FirstView> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          backgroundColor: Colors.orangeAccent,
          centerTitle: true,
          title: Text(
            'Filters',
            style: TextStyle(
              fontSize: 20,
            ),
          ),
          leading: Icon(Icons.menu),
        ),
        body: Container(
            color: Colors.white,
            child: Column(children: [
              FutureBuilder(
                future: getCars(),
                builder: (context, snapshot) {
                  if (snapshot == null) {
                    return Container(
                      child: Center(
                        child: Text('loading'),
                      ),
                    );
                  }
                  final List carList = snapshot.data.ListView.builder(
                    itemCount: snapshot.data.length,
                    itemBuilder: (BuildContext context) {
                      return ListTile(
                        title: Text(snapshot.data),
                      );
                    },
                  );
                },
              )
            ])));
  }
}

getCars() async {
  var data = await http.get("https://ven10.co/assessment/filter.json");
  var jsonData = jsonDecode(data.body);
  Autogenerated carList = Autogenerated.fromJson(jsonData);
  print(" jsonData ....");
  print(jsonData);
  print(" carList ....");
  print(carList);
  return carList;
}
